services:
  laudos-backend:
    container_name: laudos-backend
    image: ${ECR_REPO_BASE}/${COMPOSE_PROJECT_NAME}:java-${JAVA_VERSION}
    build: 
      context: .
      args:
        PLATFORM: ${PLATFORM}
        PROJECT: ${COMPOSE_PROJECT_NAME}
        JAVA_VERSION: ${JAVA_VERSION}
      platforms:
        - linux/arm64
    ports:
      - "8080:8080"
    env_file:
      - .env
      - env/${COMPOSE_PROJECT_NAME}.env
